spring:
  application:
    name: "gateway"
  profiles:
    active: "dev"
    include:
      - "route"
  main:
    banner-mode: off
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: "192.168.31.167:8848"
      discovery:
        namespace: "SCD"
        group: "DEFAULT_GROUP"

server:
  port: 80
