spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
            logger-level: basic

feign:
  sentinel:
    enabled: true
